package:
    name: cadishi
    version: "1.1.0"

source:
    path: ../../

requirements:
    build:
        - python
        - cython
        - setuptools
        - numpy
        - scipy
        - h5py
        - pyyaml
        - six
        - future

    run:
        - python
        - setuptools
        - numpy
        - scipy
        - h5py
        - pyyaml
        - six
        - future

# disabled due to glitches with the pkg cache directory
# test:
#     # test if the package can be imported
#     imports:
#         - cadishi
#         - cadishi.kernel

about:
    home: https://gitlab.mpcdf.mpg.de/MPIBP-Hummer/Cadishi
    license: MIT
    summary: 'Cadishi is a software package designed to compute (Euclidean) distance histograms efficiently.'
